apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachine
metadata:
  annotations:
    cluster.x-k8s.io/cloned-from-groupkind: DockerMachineTemplate.infrastructure.cluster.x-k8s.io
    cluster.x-k8s.io/cloned-from-name: capi-quickstart
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: capi-quickstart-control-plane
  name: capi-quickstart-control-plane-wz4w2-8lcgx
  namespace: default
spec:
  bootstrapped: true
  customImage: kindest/node:v1.27.0
  extraMounts:
    - containerPath: /var/run/docker.sock
      hostPath: /var/run/docker.sock
  providerID: docker:////capi-quickstart-w5jbn-k2hct
