apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
  name: capi-quickstart
  namespace: default
spec:
  template:
    spec:
      customImage: kindest/node:v1.27.0
      extraMounts:
        - containerPath: /var/run/docker.sock
          hostPath: /var/run/docker.sock
