apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
  name: capi-quickstart
  namespace: default
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: capi-quickstart
      uid: 42a44d23-e3fa-49a2-bb4e-0dd3c819a6f1
spec:
  template:
    spec:
      customImage: kindest/node:v1.27.0
      extraMounts:
        - containerPath: /var/run/docker.sock
          hostPath: /var/run/docker.sock
