apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: capi-quickstart
  namespace: default
spec:
  template:
    spec:
      cloudName: capo-e2e
      flavor: m1.medium
      identityRef:
        kind: Secret
        name: capi-quickstart-cloud-config
      image: focal-server-cloudimg-amd64
      sshKeyName: cluster-api-provider-openstack-sigs-k8s-io