apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: capi-quickstart
  name: capi-quickstart-w5jbn-rv4bd
  namespace: default
spec:
  clusterConfiguration:
    apiServer:
      certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
        - host.docker.internal
      extraArgs:
        cloud-provider: external
    clusterName: capi-quickstart
    controlPlaneEndpoint: 172.19.0.4:6443
    controllerManager:
      extraArgs:
        enable-hostpath-provisioner: "true"
        cloud-provider: external
    dns: {}
    etcd:
      local: {}
    kubernetesVersion: v1.27.0
    networking:
      dnsDomain: cluster.local
      podSubnet: 192.168.0.0/16
      serviceSubnet: 10.128.0.0/12
    scheduler: {}
  format: cloud-config
  initConfiguration:
    localAPIEndpoint: {}
    nodeRegistration:
      criSocket: unix:///var/run/containerd/containerd.sock
      imagePullPolicy: IfNotPresent
      kubeletExtraArgs:
        eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
