apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    cluster.x-k8s.io/paused: "true"
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: capi-quickstart-control-plane
  name: capi-quickstart-w5jbn-k2hct
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: KubeadmConfig
      name: capi-quickstart-w5jbn-rv4bd
      namespace: default
    dataSecretName: secret-dummy
  clusterName: capi-quickstart
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: InfraMachine
    name: capi-quickstart-control-plane-wz4w2-8lcgx
    namespace: default
  nodeDeletionTimeout: 10s
  providerID: docker:////capi-quickstart-w5jbn-k2hct
  version: v1.27.0
