name: CAPI Migration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docker:
    name: CAPI Migration
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Enable ipv4 and ipv6 forwarding
        run: |
          sudo sysctl -w net.ipv6.conf.all.forwarding=1
          sudo sysctl -w net.ipv4.ip_forward=1

      - name: Create Management Cluster
        run: |
          ./cluster-api-migration.sh docker purge_and_init_mgmt_cluster

      - name: Kustomize Workload Manifest
        run: |
          ./cluster-api-migration.sh docker kustomize_workload_manifest

      - name: Create Workload Cluster
        run: |
          ./cluster-api-migration.sh docker init_workload_cluster

      - name: Purge & Create Management Cluster
        run: |
          ./cluster-api-migration.sh docker purge_and_init_mgmt_cluster

      - name: Migration Phase Cluster
        run: |
          ./cluster-api-migration.sh docker migration_phase_cluster

      - name: Migration Phase Control Plane
        run: |
          ./cluster-api-migration.sh docker migration_phase_control_plane

      - name: Migration Phase Worker
        run: |
          ./cluster-api-migration.sh docker migration_phase_worker
        
      - name: Rolling Upgrade Control Plane
        run: |
          ./cluster-api-migration.sh docker rolling_upgrade_control_plane

      - name: Rolling Upgrade Worker
        run: |
          ./cluster-api-migration.sh docker rolling_upgrade_worker
